repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
  - repo: local
    hooks:
      - id: python-example-lint
        name: python-example-lint
        entry: python examples/python-example/tasks.py lint
        language: system
        pass_filenames: false
        files: ^examples/python-example/
