version: "3"

tasks:
  init:
    cmds:
      - mkdir -p .artifacts/scans
      - GRADLE_USER_HOME=.gradle gradle --no-daemon --write-locks testClasses

  lint:
    cmds:
      - GRADLE_USER_HOME=.gradle gradle --no-daemon spotlessCheck spotbugsMain spotbugsTest

  test:
    cmds:
      - GRADLE_USER_HOME=.gradle gradle --no-daemon test

  scan:
    cmds:
      - mkdir -p .artifacts/scans
      - GRADLE_USER_HOME=.gradle gradle --no-daemon testClasses
      - trivy fs --scanners vuln --format json --output .artifacts/scans/trivy-java.json .
      - gitleaks dir . --no-banner --redact --report-format sarif --report-path .artifacts/scans/gitleaks.sarif

  format:
    cmds:
      - GRADLE_USER_HOME=.gradle gradle --no-daemon spotlessApply

  ci:
    cmds:
      - task init
      - task lint
      - task test
      - task scan
