version: "3"

tasks:
  init:
    cmds:
      - python tasks.py init

  lint:
    cmds:
      - python tasks.py lint

  test:
    cmds:
      - python tasks.py test

  scan:
    cmds:
      - python tasks.py scan

  format:
    cmds:
      - python tasks.py format

  ci:
    cmds:
      - task init
      - task lint
      - task test
      - task scan
